### ISSUE TITLE
[Idea] Maybe use `mpv` instead of `vlc`

### ISSUE THREAD

**Issue by jeffshee** [jeffshee/hidamari#9]
`mpv` provides similar functionality (also support GPU video decoding). 
Both `vlc` and `mpv` support Youtube video streaming. 
(Yep, I would like to provide Youtube streaming function in the future as well!)

However `mpv` seems to work better in handling Youtube video and playlist. 
There are some videos that `vlc` couldn't play. (It returns HTTP 403 error.)
For example: https://www.youtube.com/watch?v=1vvyyhteIv4

PyGObject embedding:
https://github.com/jaseg/python-mpv#pygobject-embedding

**Comment by 94824** [comment]
Sure, sounds good!

I was messing around, and I wasn't able to get mpv to properly embed into our window, it would just be a free floating window like a normal application. I tried using the documentation's way of using a widget, and also tried to just change the existing VLCWidget class, and both would just create floating windows.

This is my current instance of the MPVWidget:

```python
class MPVWidget(Gtk.DrawingArea):
    __gtype_name__ = 'MPVWidget'

    def __init__(self, width, height):
        Gtk.DrawingArea.__init__(self)
        self.player = None

        def handle_embed(*args):
            self.player = mpv.MPV(wid=str(self.get_window().get_xid()))  # The issue is probably here.
            return True

        # Embed and set size.
        self.connect("realize", handle_embed)
        self.set_size_request(width, height)
```

I think the issue is to find an MPV command similar to set_xwindow(), but the documentation for python-mpv is sparse, or at least I can't find anything.

**Comment by jeffshee** [comment]
Hi! mpv backend is added to branch: [mpv](https://github.com/jeffshee/hidamari/tree/mpv)
It has a minor issue (refer to the TODO) but it's almost ready to go! 🎊

**Comment by 94824** [comment]
Cool! 

Is the old VLC player just there until the TODO gets weeded out, or do you want to keep both methods and use VLC as a fallback? I think it would probably be best to use one or the other.

Also, in regard to the TODO, would setting self.mpv.pause = True immediately after spawning the mpv instance not work? As I mentioned, I'm having difficulty finding much documentation on python-mpv, so I'm probably not going to be that helpful in trying to figure out the inner working of the library :)

**Comment by jeffshee** [comment]
As you mentioned, the only downside of mpv is the lack of documentation. 
That's why I keep both methods for now, just for easier testing.
Once I get everything to work as intended, I will migrate to mpv eventually.
The `master` branch will be using vlc, until the `mpv` branch is merged. 😉

IIRC I tried setting `self.mpv.pause = True` immediately after calling the `self.mpv.play()`, that didn't pause the playback immediately. I will see if we could append the file to playlist first, then play the playlist afterward.

**Comment by 94824** [comment]
Hello again!

I have some good news and some bad news

I was reading the python-mpv page to try and find some appropriate docs, and it mentioned being a copy of a lua instance, turns out there's some pretty good documentation at https://mpv.io/manual/stable/#lua-scripting. I believe that `loadfile` will fix our TODO issue with `play`. It seems to do what we want.

Now, on to the bad. I figured out why my mpv test was creating separate windows, it's wayland (of course). If you try and run our mpv setup underneath a wayland enviornment, it'll spawn mpv on a window rather than behind the deskop. It *really* sucks, because I'm not sure if there is something we *can* fix, I'd be willing to assume it's likely an mpv thing. 

I suppose we could add restrictions to mpv, only allowing it to run in a pure X environment, but what are your thoughts?  Another quick tibit, but probably nothing too important, but CPU was pretty high so I don't think mpv was using the GPU. We probably just have to toggle a flag, so I'll get back to you if I find anything!

**Comment by jeffshee** [comment]
Hi, did you tested with the latest mpv branch. Yesterday I pushed the changes that fix the mentioned minor issue, everything works fine in x11. I haven't tried with Wayland tho, will do later.

**Comment by jeffshee** [comment]
Hi, I confirmed the issue with Wayland. I pushed a fix that works fine on my side. Now mpv should fall back to x11. ^^
About the below lines:
```python
        x11 = ctypes.cdll.LoadLibrary('libX11.so')
        x11.XInitThreads()
```
I'm not sure if this is still required with mpv. As this add a dependency of package `libX11-dev`, I'd like to remove this if it does nothing. (I couldn't confirm it with Nvidia card on Wayland, yet.)

**Comment by 94824** [comment]
You're right, loading xlib is not required for mpv, and it looks like hardware acceleration is working! It's CPU usage for me is hovering around 3%, so not quite as low as vlc, but still good nontheless. 

As for wayland, it's still not working on my end. I grabbed the latest from the mpv branch. It crashes when trying to initialize a player using the `gpu_context="x11"` argument when initializing the player. Is yours working in wayland the way we want, or does it just fallback to vlc? I removed the argument, and it pops up the mpv player in a separate window.

Also, did you say you fixed the issue with the TODO? To be honest, I wasn't exactly sure what the problem was.

**Comment by jeffshee** [comment]
Thanks for the confirmation!

>It crashes when trying to initialize a player using the gpu_context="x11" argument when initializing the player. Is yours working in wayland the way we want, or does it just fallback to vlc? I removed the argument, and it pops up the mpv player in a separate window.

Weird... It works fine in my Wayland session, the window shown on the desktop.
(I tested using 3 PC, all with Nvidia cards... Might be Wayland+HW specific? )
Maybe the `hwdec` didn't work well in the Wayland. How about `hwdec=auto-safe` or `hwdec=no`? Also, did the terminal output some error messages during the crash?

>Also, did you say you fixed the issue with the TODO? To be honest, I wasn't exactly sure what the problem was.

Yes. The problem was, the mpv initialized without the `pause=True` will start the playback immediately soon after `mpv.Play` function is called. As a result, there was a tiny time gap which we couldn't pause or mute the playback (according on the situation) in between.

Well, to be honest, I never thought that mpv was more difficult than vlc. Now I feel that vlc is a better option in term of stability in our usecase. So, let's use vlc for now, so that we can invest our time in more exciting features! About the YouTube error, we can file a bug ticket to vlc team. Hopefully, we will get the fix soon. ;-)

**Comment by 94824** [comment]
My only thought for why your's might work is because Wayland on Nvidia uses those EGLStreams, which my Intel GPU would not. Strange though. here's a stacktrace of the crash, if it helps you any:

```Traceback (most recent call last):
  File "hidamari/src/hidamari", line 26, in <module>
    Player()
  File "hidamari/src/player_mpv.py", line 73, in __init__
    self.mpv_widget = MPVWidget(self.width, self.height)
  File "hidamari/src/player_mpv.py", line 28, in __init__
    self.player = mpv.MPV(log_handler=print, input_cursor=False, pause=True, loop=True, gpu_context="x11", hwdec="auto")
  File "/usr/lib/python3.9/site-packages/mpv.py", line 820, in __init__
    _mpv_set_option_string(self.handle, k.replace('_', '-').encode('utf-8'), istr(v).encode('utf-8'))
  File "/usr/lib/python3.9/site-packages/mpv.py", line 133, in raise_for_ec
    raise ex(ec, *args)
ValueError: ('Invalid value for mpv option', -7, (<MpvHandle object at 0x7fe8ece50140>, b'gpu-context', b'x11'))
```

I'd say you're probably right on sticking with VLC, for no other reason than it's got [really good docs](https://www.olivieraubert.net/vlc/python-ctypes/doc/). I have a feeling that mpv might be harder to maintain in the future, but I dunno. 

A little glimmer of hope for VLC, however, is that I can play the video you mentioned on VLC on Android using the [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor), so I believe it's entirely feasible--we might just have to do some work extracting a valid URL? I'm certainly not advoacting we should use the extractor in Hidamari :) just that it seems we can get VLC to play the video if we mess around with it.

**Comment by jeffshee** [comment]
Closed. I had found a way to stream Youtube into VLC, using `youtube-dl` as backend. This might open up an opportunity for other streaming sites as well, as long as `youtube-dl` support.
